PR 1 for v1.15.0 (Changes Related to New Connector Development, Etc.)
hms-networks/sc-ewon-flexy-extensions-lib pull request #60
Opened 2023-09-25 12:38 UTC by alexjhawk

This is PR 1 in a series of pull requests to bring in changes for v1.15.0. These are mostly related to the development of a new connector, staged changes that were previously untested, and other changes or enhancements, as described.

2023-09-26 14:16 UTC, it-hms requested changes

2023-09-26 14:18 UTC, alexjhawk commented on .vscode/tasks.json
> +            "label": "INSTALL (Upload to Device)",
This was incorrectly labeled previously. Our architecture's `install` lifecycle is modified to upload the artifact to the device. See: https://hms-networks.github.io/sc-java-maven-starter-project/docs/developer/maven-lifecycles

2023-09-27 13:02 UTC, alexjhawk commented on src/main/java/com/hms_networks/americas/sc/extensions/system/time/SCTimeSpan.java
> + * specified unit.
Added

2023-09-27 18:00 UTC, oliver-walker-hms approved these changes

2023-09-27 18:00 UTC, merged