Add data poll blocking to framework
hms-networks/sc-ewon-flexy-extensions-lib pull request #89
Opened 2024-02-27 14:38 UTC by alexjhawk

Added support for blocking data polling to the
connector framework. Data poll blocking is a
separate feature from enable/disable, as data
poll blocking is intended for temporary error
conditions, not a user selection via tag/API.

2024-02-27 22:09 UTC, it-hms approved these changes

2024-02-28 20:26 UTC, TomKimsey requested changes
Looks like 02-CHANGELOG.md got formatted in your release commit. This formatting should be moved to a separate commit or removed.

2024-02-28 20:29 UTC, alexjhawk commented
> Looks like 02-CHANGELOG.md got formatted in your release commit. This formatting should be moved to a separate commit or removed.

Added a separate commit

2024-02-28 21:24 UTC, it-hms approved these changes

2024-02-28 21:28 UTC, alexjhawk commented
> It would be nice to have some formatting rule or explanation in the format commit to what the line length you are targeting in .mdx files.

This is formatted to the standard Google code style length of 100.

2024-02-28 21:28 UTC, merged